name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: ${{ matrix.os }}-py3.6
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.6
          conda-channels: anaconda, conda-forge
      - name: Get conda version
        run: conda --version
      - name: Install dependencies
        run: |
          conda install coverage flake8 Flask Flask-RESTful imutils dlib opencv numpy pytest requests
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
      - name: Test with pytest
        run: |
          pip install -e .
          screen -d -m -S server bash -c "python googlyeyes/server.py"
          pytest
