name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:

    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        update-conda: true
        python-version: 3.6
        conda-channels: anaconda, conda-forge defaults menpo
    - name: Install dependencies
      run: |
        conda --version
        conda env create -f environment.yml
        conda activate googlyeyes
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    # - name: Lint with black
    #   run: black . --line-length 79 --check
    - name: Test with pytest
      run: |
        pip install -e .
        pytest
